spring.application.name=bookmyshow-show-service
server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/bookmyshow_show
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:@Shawn123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/bookmyshow

# Eureka Service Discovery configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

services.movie.base-url=http://bookmyshow-movie-service
services.theatre.base-url=http://bookmyshow-theatre-service
services.booking.base-url=http://bookmyshow-booking-service

services.auth.token-url=http://localhost:8080/realms/bookmyshow/protocol/openid-connect/token
services.auth.client-id=bookmyshow-admin
services.auth.client-secret=${KEYCLOAK_CLIENT_SECRET:B6LqV8a3DaiqBptjyYbXABFCv8RXCvdi}

spring.profiles.active=local

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.timeout=6000ms

spring.cache.type=redis

booking.seat-hold.seconds=300

# Resilience4j Circuit Breaker configuration
resilience4j.circuitbreaker.instances.redisHold.sliding-window-type=count_based
resilience4j.circuitbreaker.instances.redisHold.sliding-window-size=10
resilience4j.circuitbreaker.instances.redisHold.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.redisHold.wait-duration-in-open-state=10000ms
resilience4j.circuitbreaker.instances.redisHold.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.redisRelease.sliding-window-size=10
resilience4j.circuitbreaker.instances.redisRelease.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.redisConfirm.sliding-window-size=10
resilience4j.circuitbreaker.instances.redisConfirm.failure-rate-threshold=50
