spring.application.name=bookmyshow-eureka-server
server.port=8761

# Disable Eureka Dashboard registration with itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka service URL endpoint configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
